In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import sys
sys.path.append('../Auxiliary_Functions/')
from phi import phi
sys.path.append('../MRC/')
from MRC import MRC
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('../synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

#print("The training samples are,")
#print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6


In [2]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma,D):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl(False,True,'linear',2,0.3,'log',sigma_,2)

In [3]:
Prueba1 = MRC.parameters(Prueba1,xtr,ytr)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 0.45453698 -0.15402685 -0.40760802 -0.06814355]
El vector lambda es,
[[0.04232385 0.05366596 0.0305373  0.03793817]]


In [4]:
Prueba1 = MRC.learning(Prueba1,xtr)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The value of the MRC optimization problem is", Prueba1.RU)

El vector mu es,
[ 1.30502875e-09  1.78764819e-09 -3.26906164e+00 -3.02247446e-01]
The value of the MRC optimization problem is 0.2949167474701987


In [5]:
Prueba1 = MRC.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)

El error de clasificación es
0.0
