In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import sys
sys.path.append('../Auxiliary_Functions/')
from phi import phi
sys.path.append('../Robust/')
from Robust import Robust
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('../synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

#print("The training samples are,")
#print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6


In [2]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma

Prueba1 = Mdl(False,True,'linear',2,0.3,'0-1',sigma_)

Prueba1 = Robust.LREIW(Prueba1,xtr,xte)

print("The alpha weights for training are,")
print(Prueba1.alpha_tr_.T)
print("The alpha weights for testing are,")
print(Prueba1.alpha_.T)

The alpha weights for training are,
[[0.7651604  0.62013401 0.35640214 0.71527568 0.90029038 0.39766579
  0.84669313 0.61348308 0.67747743 1.31086865 1.68808602 1.26505664
  0.74023677 0.66000989 1.27983696 0.84159139 0.68725157 1.00107732
  1.11888227 1.41053388 0.67448272 2.16265817 0.75549756 2.6021804
  1.3314788 ]]
The alpha weights for testing are,
[[0.85939071 0.85948992 1.31285196 1.53525687 1.50301691 1.77311773
  0.88083201 0.973965   2.00351931 0.53701623 0.80111815 1.49678086
  0.4041556  1.46397709 1.42162653 0.91986736 1.21259198 1.06320187
  1.19407439 1.67820621 1.0963643  0.75463865 1.04356976 1.02712734
  1.3801495 ]]


In [3]:
Prueba1 = Robust.parameters(Prueba1,xtr,ytr)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 0.45453698 -0.15402685 -0.40760802 -0.06814355]
El vector lambda es,
[[0.04232385 0.05366596 0.0305373  0.03793817]]


In [4]:
Prueba1 = Robust.learning(Prueba1,xtr)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The value of the MRC optimization problem is", Prueba1.RU)

El vector mu es,
[ 6.67018181e-11  4.78951324e-11 -3.41397034e+00 -1.05304719e-01]
The value of the MRC optimization problem is 0.19579616512471965


In [5]:
Prueba1 = Robust.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)

El error de clasificación es
0.0
