In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
from Auxiliary_Functions.phi import phi 
from DWGCS.DWGCS import DWGCS
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

print("The training samples are,")
print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6
The training samples are,
[[ 1.83111752 -0.62883089  1.        ]
 [-0.82016248 -1.11608551  2.        ]
 [ 0.89632522 -2.41402695  1.        ]
 [ 1.97949737 -0.78672012  1.        ]
 [ 0.22335683 -0.24598268  1.        ]
 [ 1.63128782 -2.1589984   1.        ]
 [-0.56673224 -0.38827161  2.        ]
 [ 1.22686954 -1.14452834  1.        ]
 [-0.38198907 -0.90995838  2.        ]
 [-0.11761212  0.63319238  1.        ]
 [-1.52525253  1.22682911  2.        ]
 [ 0.94089234  0.54833618  1.        ]
 [ 0.93998732 -0.70486621  1.        ]
 [-0.32097257 -0.97113935  2.        ]
 [-0.49956809  0.57777049  2.        ]
 [-1.02153375 -0.40168784  2.        ]
 [-1.01600576 -0.87546186  2.        ]
 [-0.99638883  0.00408872  2.        ]
 [-1.54581123  0.26512044  2.        ]
 [ 1.87479008  0.80141221  1.        ]
 [-0.40589332 -0.92028062  2.        ]
 [-1.08989071  1.8054877   2.        ]
 [-0.10702678 -0.65549526  1.        ]
 [ 0.06554551  2.23631475  1.        ]
 [-0.02160612

In [2]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma,D):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl(False,False,'linear',2,0,'0-1',sigma_,2)

Prueba1 = DWGCS.DWKMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The alpha weights are,")
print(Prueba1.alpha_)
print("The optimization value of the DW-KMM is", Prueba1.min_DWKMM)

The beta weights are,
[[0.39680311]
 [0.30151541]
 [0.11399322]
 [0.33411753]
 [1.26245035]
 [0.12910804]
 [0.86248074]
 [0.27612227]
 [0.39521843]
 [1.45013898]
 [0.61770323]
 [2.03483236]
 [0.45634117]
 [0.36599165]
 [1.22973161]
 [0.70991064]
 [0.38894858]
 [1.02988425]
 [0.74452656]
 [0.87168754]
 [0.38958218]
 [0.67270035]
 [0.57930055]
 [0.79451412]
 [1.45362967]]
The alpha weights are,
[[0.70374927]
 [0.71779026]
 [0.69796148]
 [0.70305962]
 [0.70249616]
 [0.7366363 ]
 [0.70218526]
 [0.69480841]
 [0.734775  ]
 [0.79881005]
 [0.7294877 ]
 [0.70310475]
 [0.82069608]
 [0.70692825]
 [0.6984691 ]
 [0.70007264]
 [0.69130792]
 [0.6913624 ]
 [0.70160677]
 [0.71519112]
 [0.69560114]
 [0.71944851]
 [0.69160626]
 [0.69631278]
 [0.70790659]]
The optimization value of the DW-KMM is 5.02947788319976e-10


In [3]:
Prueba1 = DWGCS.parameters(Prueba1,xtr,ytr,xte)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 0.2434947   0.12353305 -0.26999003  0.02055277]
El vector lambda es,
[1.13530597e-02 5.78258501e-04 1.15112160e-02 1.00000376e-06]


In [4]:
Prueba1 = DWGCS.learning(Prueba1,xte)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The value of the MRC optimization problem using weights beta obtained using DWKMM is", Prueba1.RU)

El vector mu es,
[ 7.01986908  1.07576182 -8.22937872 -1.07654679]
The value of the MRC optimization problem using weights beta obtained using DWKMM is 0.01281262083946999


In [5]:
Prueba1 = DWGCS.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)

El error de clasificación es
0.04
