In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import sys
sys.path.append('../Auxiliary_Functions/')
from phi import phi
sys.path.append('../Reweighted/')
from Reweighted import Reweighted
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('../synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

print("The training samples are,")
print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6
The training samples are,
[[ 1.83111752 -0.62883089  1.        ]
 [-0.82016248 -1.11608551  2.        ]
 [ 0.89632522 -2.41402695  1.        ]
 [ 1.97949737 -0.78672012  1.        ]
 [ 0.22335683 -0.24598268  1.        ]
 [ 1.63128782 -2.1589984   1.        ]
 [-0.56673224 -0.38827161  2.        ]
 [ 1.22686954 -1.14452834  1.        ]
 [-0.38198907 -0.90995838  2.        ]
 [-0.11761212  0.63319238  1.        ]
 [-1.52525253  1.22682911  2.        ]
 [ 0.94089234  0.54833618  1.        ]
 [ 0.93998732 -0.70486621  1.        ]
 [-0.32097257 -0.97113935  2.        ]
 [-0.49956809  0.57777049  2.        ]
 [-1.02153375 -0.40168784  2.        ]
 [-1.01600576 -0.87546186  2.        ]
 [-0.99638883  0.00408872  2.        ]
 [-1.54581123  0.26512044  2.        ]
 [ 1.87479008  0.80141221  1.        ]
 [-0.40589332 -0.92028062  2.        ]
 [-1.08989071  1.8054877   2.        ]
 [-0.10702678 -0.65549526  1.        ]
 [ 0.06554551  2.23631475  1.        ]
 [-0.02160612

In [2]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma

Prueba1 = Mdl(False,True,'linear',2,0.3,'0-1',sigma_)

Prueba1 = Reweighted.KMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The optimization value of the DW-KMM is", Prueba1.min_KMM)

The beta weights are,
[[0.47333497]
 [0.48342566]
 [0.2176083 ]
 [0.41500316]
 [0.99407732]
 [0.22694316]
 [0.89867982]
 [0.38541998]
 [0.55485796]
 [2.88401943]
 [0.83799069]
 [2.32397662]
 [0.54866009]
 [0.52650531]
 [2.2215274 ]
 [0.85854705]
 [0.57881704]
 [1.22428237]
 [1.10283165]
 [1.41470482]
 [0.55109548]
 [0.70207404]
 [0.67631675]
 [0.80689083]
 [3.0923068 ]]
The optimization value of the DW-KMM is 3.70059308834223e-10


In [3]:
Prueba1 = Reweighted.parameters(Prueba1,xtr,ytr)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 0.31509986  0.198157   -0.36213242  0.02452531]
El vector lambda es,
[0.04087272 0.04508653 0.0299322  0.02925585]


In [4]:
Prueba1 = Reweighted.learning(Prueba1,xtr)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The value of the MRC optimization problem using weights beta obtained using KMM is", Prueba1.RU)

El vector mu es,
[ 2.92118288e-12  1.88429580e-12 -1.61496062e+00 -4.21011218e-01]
The value of the MRC optimization problem using weights beta obtained using KMM is 0.21748762915477116


In [5]:
Prueba1 = Reweighted.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)


El error de clasificación es
0.04
