In [12]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import sys
sys.path.append('../Auxiliary_Functions/')
from phi import phi
sys.path.append('../Reweighted/')
from Reweighted import Reweighted
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('../synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

#print("The training samples are,")
#print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6


In [13]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma

Prueba1 = Mdl(False,True,'linear',2,0.3,'0-1',sigma_)

Prueba1 = Reweighted.LREIW(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_.T)

The beta weights are,
[[1.30691551 1.61255468 2.80581928 1.39806235 1.11075274 2.51467447
  1.18106544 1.63003679 1.47606394 0.76285294 0.59238687 0.79047844
  1.35091911 1.51512882 0.78134952 1.18822509 1.45507124 0.99892384
  0.89374908 0.70895142 1.48261766 0.46239393 1.32363102 0.38429311
  0.75104463]]


In [14]:
Prueba1 = Reweighted.parameters(Prueba1,xtr,ytr)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 0.68583646 -0.60944121 -0.42042947 -0.23737521]
El vector lambda es,
[0.06872693 0.10385631 0.03053692 0.04017239]


In [15]:
Prueba1 = Reweighted.learning(Prueba1,xtr)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The value of the MRC optimization problem using weights beta obtained using KMM is", Prueba1.RU)

El vector mu es,
[ 1.09618332e-14  5.15956147e-15 -1.91280924e+00 -2.95978118e-01]
The value of the MRC optimization problem using weights beta obtained using KMM is 0.15815551923571247


In [16]:
Prueba1 = Reweighted.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)

El error de clasificación es
0.04
