In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from Weight_Functions.DWKMM import DWKMM
from UncertaintySet_Functions.DWGCS_parameters import DWGCS_parameters 
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[0.39765399 0.18269515 0.56140212]
 [0.49877848 0.13222659 0.19466994]
 [0.3621351  0.34982536 0.47848017]
 [0.69857544 0.74249732 0.68810539]
 [0.0810347  0.05579363 0.5543034 ]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.sigma_ = sigma
        self.D = D

DWGCS = Mdl('bias','linear',2,0.3,1,1)

DWGCS = DWKMM(DWGCS,xtr,xte)
print("The beta weights are,")
print(DWGCS.beta_)
print("The alpha weights are,")
print(DWGCS.alpha_)
print("The optimization value of the DW-KMM is", DWGCS.min_DWKMM)

The beta weights are,
[5.86742584e-09 1.71065660e+00 5.31822307e-09 6.46321274e-08
 5.25411300e-01]
The alpha weights are,
[1. 1. 1.]
The optimization value of the DW-KMM is 1.772263289243987


In [3]:
DWGCS = DWGCS_parameters(DWGCS,xtr,ytr,xte)

print("El vector tau es,")
print( DWGCS.tau_)
print("El vector lambda es,")
print( DWGCS.lambda_)

El vector tau es,
[1.51635553e-08 9.88190742e-09 1.01843161e-08 1.00624729e-08
 4.47213580e-01 1.79163049e-01 5.11017778e-02 1.24850137e-01]
El vector lambda es,
[0.51979371 0.51979372 0.51979372 0.51979372 0.07258015 0.34063068
 0.46869195 0.39494359]
