In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from DWGCS.DWGCS import DWGCS
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[9.56377466e-02 9.34607528e-01 3.96227247e-01]
 [7.05163307e-01 2.08612006e-01 2.85484076e-04]
 [2.36044290e-01 2.08076131e-01 7.02590911e-01]
 [8.17232645e-01 5.85897100e-01 5.92498494e-01]
 [6.38545688e-02 9.25343018e-01 3.71978531e-01]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,loss,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl('bias','linear',2,0.3,'0-1',1,1)

Prueba1 = DWGCS.DWKMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The alpha weights are,")
print(Prueba1.alpha_)
print("The optimization value of the DW-KMM is", Prueba1.min_DWKMM)

The beta weights are,
[1.01765578e-07 1.59263987e+00 1.78119257e-08 2.69724894e-08
 6.43427962e-01]
The alpha weights are,
[1. 1. 1.]
The optimization value of the DW-KMM is 1.568405361784472


In [3]:
Prueba1 = DWGCS.parameters(Prueba1,xtr,ytr,xte)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[2.93099986e-08 7.19596655e-09 2.29240430e-08 1.37635902e-08
 4.47213566e-01 2.32831402e-01 1.85527074e-01 4.79592123e-02]
El vector lambda es,
[0.60783144 0.60783146 0.60783145 0.60783146 0.17502199 0.37500007
 0.4223044  0.55987226]


In [4]:
Prueba1 = DWGCS.learning(Prueba1,xte)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The optimization value of the DW-GCS is", Prueba1.RU)

El vector mu es,
[-1.17748076e-11 -1.42241463e-12 -2.33266198e-12 -1.74783612e-12
 -2.53640418e-11  2.24250147e-12 -8.23681866e-13 -1.24004279e-12]
The optimization value of the DW-GCS is 0.5000000000088614
