In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from DWGCS.DWGCS import DWGCS
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[0.75154796 0.3860992  0.21586961]
 [0.30449419 0.59561448 0.502205  ]
 [0.92978532 0.84679605 0.39813308]
 [0.30753691 0.82140022 0.15427817]
 [0.4506343  0.16498549 0.93883529]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl('bias','linear',2,0.3,1,1)

Prueba1 = DWGCS.DWKMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The alpha weights are,")
print(Prueba1.alpha_)
print("The optimization value of the DW-KMM is", Prueba1.min_DWKMM)

The beta weights are,
[2.92698329e-01 1.14637331e-08 1.94336948e+00 8.92798998e-08
 6.11724910e-08]
The alpha weights are,
[1. 1. 1.]
The optimization value of the DW-KMM is 1.7217321563977177


In [3]:
Prueba1 = DWGCS.parameters(Prueba1,xtr,ytr,xte)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[4.47213580e-01 4.05378656e-01 3.51729654e-01 1.67380875e-01
 1.45272448e-08 6.21141260e-09 3.38410772e-09 1.26376075e-08]
El vector lambda es,
[0.12824583 0.0864109  0.12853281 0.31288158 0.48026244 0.48026245
 0.48026246 0.48026245]
