In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from Weight_Functions.DWKMM import DWKMM
from UncertaintySet_Functions.DWGCS_parameters import DWGCS_parameters 
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[0.45267769 0.135091   0.76824318]
 [0.93262683 0.65413991 0.68497534]
 [0.28149606 0.22332421 0.61779523]
 [0.6257241  0.66145831 0.73706188]
 [0.37328499 0.75383719 0.21196334]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.sigma_ = sigma
        self.D = D

DWGCS = Mdl('bias','linear',2,0.3,1,1)

DWGCS = DWKMM(DWGCS,xtr,xte)
print("The beta weights are,")
print(DWGCS.beta_)
print("The alpha weights are,")
print(DWGCS.alpha_)
print("The optimization value of the DW-KMM is", DWGCS.min_DWKMM)

The beta weights are,
[[1.63243004e+00]
 [6.08224246e-09]
 [1.10768969e-08]
 [1.71532497e-09]
 [6.03637918e-01]]
The alpha weights are,
[[1.]
 [1.]
 [1.]]
The optimization value of the DW-KMM is 1.6824389617419213


In [3]:
DWGCS = DWGCS_parameters(DWGCS,xtr,ytr,xte)

print("El vector tau es,")
print( DWGCS.tau_)
print("El vector lambda es,")
print( DWGCS.lambda_)

El vector tau es,
[[0.32648601 0.14779293 0.04410532 0.25082065 0.12072758 0.0450658
  0.09100894 0.02558982]]
El vector lambda es,
[[0.20332502 0.3820181  0.48570571 0.27899038 0.40908345 0.48474524
  0.43880209 0.50422121]]


/Users/jsegovia/.conda/envs/CovariateShift/lib/python3.8/site-packages/cvxpy/expressions/expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)
/Users/jsegovia/.conda/envs/CovariateShift/lib/python3.8/site-packages/cvxpy/expressions/expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 2 times so far.