In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
from Auxiliary_Functions.phi import phi 
from DWGCS.DWGCS import DWGCS
# Datos de ejemplo
# np.random.seed(1)
# x = np.random.multivariate_normal([0,0],[[1,0],[0,1]],50)
# y = np.zeros([50,1])
# for i in range(x.shape[0]):
#    if x[i,0] >= 0:
#        y[i] = int(1)
#    else:
#        y[i] = int(2)
#x = (x-np.mean(x,axis=0))/np.std(x,axis=0)
# m = x.shape[1]
# _, distances = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(x).kneighbors(x)
# sigma_ = np.mean(distances[:, -1])

# np.savetxt('synthetic_trial.csv', np.concatenate((x,y), axis=1), delimiter=',')

data = np.genfromtxt('synthetic_trial.csv', delimiter=',') 

xtr = data[:25,:2]
xte = data[25:,:2]
ytr = data[:25,2:].astype(int)
yte = data[25:,2:].astype(int)
m = xtr.shape[1]
sigma_ = 26.6

print("The sigma value is,", sigma_)

print("The training samples are,")
print(np.concatenate((xtr,ytr), axis=1))

The sigma value is, 26.6
The training samples are,
[[ 1.83111752 -0.62883089  1.        ]
 [-0.82016248 -1.11608551  2.        ]
 [ 0.89632522 -2.41402695  1.        ]
 [ 1.97949737 -0.78672012  1.        ]
 [ 0.22335683 -0.24598268  1.        ]
 [ 1.63128782 -2.1589984   1.        ]
 [-0.56673224 -0.38827161  2.        ]
 [ 1.22686954 -1.14452834  1.        ]
 [-0.38198907 -0.90995838  2.        ]
 [-0.11761212  0.63319238  1.        ]
 [-1.52525253  1.22682911  2.        ]
 [ 0.94089234  0.54833618  1.        ]
 [ 0.93998732 -0.70486621  1.        ]
 [-0.32097257 -0.97113935  2.        ]
 [-0.49956809  0.57777049  2.        ]
 [-1.02153375 -0.40168784  2.        ]
 [-1.01600576 -0.87546186  2.        ]
 [-0.99638883  0.00408872  2.        ]
 [-1.54581123  0.26512044  2.        ]
 [ 1.87479008  0.80141221  1.        ]
 [-0.40589332 -0.92028062  2.        ]
 [-1.08989071  1.8054877   2.        ]
 [-0.10702678 -0.65549526  1.        ]
 [ 0.06554551  2.23631475  1.        ]
 [-0.02160612

In [2]:
class Mdl:
    def __init__(self,intercep,deterministic,feature_map,labels,lambda0,loss,sigma,D):
        self.intercep = intercep
        self.deterministic = deterministic
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl(True,True,'linear',2,0.3,'0-1',sigma_,1)

Prueba1 = DWGCS.DWKMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The alpha weights are,")
print(Prueba1.alpha_)
print("The optimization value of the DW-KMM is", Prueba1.min_DWKMM)

The beta weights are,
[[9.69147804e-06]
 [7.61347129e-06]
 [7.18827000e-05]
 [1.23309684e-05]
 [5.11388217e-06]
 [4.99872526e+00]
 [5.73773426e-06]
 [7.64375785e-06]
 [6.02076659e-06]
 [5.83498583e-06]
 [3.35088063e-05]
 [6.17745919e-06]
 [5.91771666e-06]
 [6.05171211e-06]
 [6.20651192e-06]
 [6.93913968e-06]
 [7.69818444e-06]
 [6.80322842e-06]
 [1.13712318e-05]
 [1.33711801e-05]
 [6.07390717e-06]
 [1.44994663e-04]
 [5.41809773e-06]
 [8.76452470e-04]
 [5.84048792e-06]]
The alpha weights are,
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
The optimization value of the DW-KMM is 1.434921272073922


In [3]:
Prueba1 = DWGCS.parameters(Prueba1,xtr,ytr,xte)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[ 1.99990037e-01  3.26182770e-01 -4.31618606e-01  9.96077429e-06
 -1.07083363e-05  1.08930737e-05]
El vector lambda es,
[0.22926746 0.35546019 0.50856632 0.07693775 0.07695842 0.07693682]


In [4]:
Prueba1 = DWGCS.learning(Prueba1,xte)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The optimization value of the DW-GCS is", Prueba1.RU)

ValueError: Cannot broadcast dimensions  (1, 25) (25,)

In [ ]:
Prueba1 = DWGCS.prediction(Prueba1,xte,yte)

print("El error de clasificación es",)
print( Prueba1.error)
print("The classification rule h is",)
print( Prueba1.h)