In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from Weight_Functions.DWKMM import DWKMM
from UncertaintySet_Functions.DWGCS_parameters import DWGCS_parameters 
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[0.00571509 0.06377293 0.95363427]
 [0.90435943 0.20421178 0.18975671]
 [0.38307613 0.08624906 0.72786834]
 [0.18881069 0.92398051 0.96326307]
 [0.86637624 0.41733855 0.28468329]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.sigma = sigma
        self.D = D

DWGCS = Mdl('bias','linear',2,0.3,1,1)

DWGCS = DWKMM(DWGCS,xtr,xte)
print("The beta weights are,")
print(DWGCS.beta)
print("The alpha weights are,")
print(DWGCS.alpha)
print("The optimization value of the DW-KMM is", DWGCS.min_DWKMM)

The beta weights are,
[[1.13675136e+00]
 [1.09931655e+00]
 [1.25796824e-08]
 [2.95674934e-08]
 [2.26438258e-08]]
The alpha weights are,
[[1.]
 [1.]
 [1.]]
The optimization value of the DW-KMM is 1.5163960887322627


In [3]:
DWGCS = DWGCS_parameters(DWGCS,xtr,ytr,xte)

print("El vector tau es,")
print( DWGCS.tau)

El vector tau es,
[[0.22735028 0.00129933 0.0144988  0.21680902 0.21986331 0.19883546
  0.04489868 0.04172054]]
