In [1]:
import numpy as np
from Auxiliary_Functions.phi import phi 
from DWGCS.DWGCS import DWGCS
# Datos de ejemplo
xtr = np.random.rand(5, 3)  # Ejemplo de datos de entrenamiento (5 filas, 3 columnas)
xte = np.random.rand(3, 3)  # Ejemplo de datos de prueba (3 filas, 3 columnas)
ytr = np.array([[1],[2],[1],[1],[2]]) 

print("The training samples are,")
print(xtr)

The training samples are,
[[0.64146221 0.35677471 0.8394041 ]
 [0.74509295 0.48104853 0.63056106]
 [0.38971448 0.37713305 0.04052072]
 [0.96003893 0.65703482 0.26870103]
 [0.43120746 0.79140271 0.37169898]]


In [2]:
class Mdl:
    def __init__(self,bias,feature_map,labels,lambda0,loss,sigma,D):
        self.bias = bias
        self.feature_map = feature_map
        self.labels = labels
        self.lambda0 = lambda0 
        self.loss = loss
        self.sigma_ = sigma
        self.D = D

Prueba1 = Mdl('bias','linear',2,0.3,'0-1',1,1)

Prueba1 = DWGCS.DWKMM(Prueba1,xtr,xte)
print("The beta weights are,")
print(Prueba1.beta_)
print("The alpha weights are,")
print(Prueba1.alpha_)
print("The optimization value of the DW-KMM is", Prueba1.min_DWKMM)

The beta weights are,
[5.89868534e-02 8.14556491e-09 1.77431945e+00 4.02761657e-01
 6.22521416e-09]
The alpha weights are,
[1. 1. 1.]
The optimization value of the DW-KMM is 1.7167382567306646


In [3]:
Prueba1 = DWGCS.parameters(Prueba1,xtr,ytr,xte)

print("El vector tau es,")
print( Prueba1.tau_)
print("El vector lambda es,")
print( Prueba1.lambda_)

El vector tau es,
[4.47213592e-01 2.23196539e-01 1.90965590e-01 4.59265968e-02
 2.87415581e-09 1.75071235e-09 1.76901268e-09 1.49003636e-09]
El vector lambda es,
[0.13598676 0.36000382 0.39223476 0.53727376 0.58320035 0.58320035
 0.58320035 0.58320035]


In [4]:
Prueba1 = DWGCS.learning(Prueba1,xte)

print("El vector mu es,")
print( np.ravel(Prueba1.mu_))
print("The optimization value of the DW-GCS is", Prueba1.RU)

El vector mu es,
[-7.31406448e-11 -8.11988849e-13 -4.84742045e-12 -2.58154828e-12
 -2.27250621e-11 -3.35146230e-12 -4.97614698e-12 -2.99268440e-12]
The optimization value of the DW-GCS is 0.500000000015334
